// Labels follow the pinned assembly report and the individual STL geometry.
// Keep vendor references where the export does not provide a descriptive name.
export const PARTS = {
  top_enclosure: ['Upper chassis enclosure', 'Upper shell around the body.'],
  bottom_enclosure: ['Lower chassis enclosure', 'Lower shell around the body.'],
  bottom_plate: ['Chassis base plate', '1.6 mm plate inside the enclosure.'],
  standoff_plate: ['Chassis side support', '130 mm support between the enclosure plates.'],
  standoff_plate__2: ['Chassis end support', '90 mm support between the enclosure plates.'],
  first_joint_top: ['Coxa upper plate', 'Upper plate of the hip assembly.'],
  first_joint_bottom_plate: ['Coxa lower bracket', 'Lower plate and side support of the hip assembly.'],
  first_joint_spacer: ['Coxa spacer', 'Separates the hip assembly plates.'],
  femur_plate: ['Femur motor-side plate', 'Structural side plate of the upper leg.'],
  femur_plate_non_motor: ['Femur opposite-side plate', 'Structural plate opposite the motor-side plate.'],
  femur_plate_motor_spacer: ['Femur motor spacer', '5 mm spacer at the motor-side plate.'],
  femur_plate_cover_large: ['Large femur cover', 'Protective cover over the upper-leg side plate.'],
  femur_plate_cover_small: ['Small femur cover', 'Protective cover on the opposite side of the upper leg.'],
  machined_tibia: ['Tibia lower-leg frame', 'Main lower-leg structure extending to the foot.'],
  silicone_foot: ['Silicone foot pad', 'Ground-contact pad at the end of the leg.'],
  tibia_narrow_insert: ['Tibia pivot insert', 'Narrow insert inside the lower-leg pivot.'],
  tibia_spacer: ['Tibia pivot spacer', '2.5 mm spacer at the lower-leg pivot.'],
  bearing_insert: ['Bearing support insert', '31 mm insert supporting the pivot bearing.'],
  tibia_push_lever: ['Tibia drive lever', 'Transfers motor rotation to the pushrod.'],
  tibia_pushrod: ['Tibia pushrod', 'Connects the drive lever to the lower-leg linkage.'],
  tibia_pushrod_cover: ['Tibia drive-lever cover', 'Cover over the lever and pushrod connection.'],
  screw_head_cap: ['Hip screw-head cover', '46 mm cover over the hip fasteners.'],
  motor_bearing_holder: ['Motor bearing holder', 'Supports the bearing at the actuator mount.'],
  motor_flange: ['Motor mounting flange', 'Connects the actuator output to the supporting structure.'],
  motor_0001755650_00mini_000: ['Motor output hub', 'RS05 output-side hub; CAD ref. 0001755650.'],
  motor_0001755652_00mini_000: ['Motor gearbox pin', '4 mm diameter, 14 mm long; CAD ref. 0001755652.'],
  motor_0001755652_1_1_30_gr_2202: ['Motor gearbox pin', '4 mm diameter, 14 mm long; CAD ref. GR-2202.'],
  motor_1_1_02_eb461_502: ['Motor housing ring', '46 mm housing ring; CAD ref. EB461-502.'],
  motor_1_1_06_eb463_507: ['Motor', 'RS05 actuator casing; CAD ref. EB463-507.'],
  motor_1_1_06_eb463_509: ['Motor end cover', 'Rear enclosure cover; CAD ref. EB463-509.'],
  motor_1_1_31_eb463_510: ['Motor retaining plate', '2.5 mm end plate; CAD ref. EB463-510.'],
  motor_1_21_121000022__610001_1_1_00mini_000: ['Motor miniature bearing', '11 mm outer diameter, 4 mm wide; CAD ref. 610001.'],
  motor_6706__300001_1_1_00mini_000: ['Motor output bearing', '6706 bearing, 37 mm outer diameter and 4 mm wide.'],
  motor_1_2_05_000438: ['Motor countersunk screw', '4 mm long; CAD ref. 000438.'],
  motor_1_2_05_000555: ['Motor countersunk screw', '6 mm long; CAD ref. 000555.'],
  motor_1_2_05_000608: ['Motor countersunk screw', '10 mm long; CAD ref. 000608.'],
  motor_1_2_05_020051: ['Motor headed fastener', '4 mm head diameter; CAD ref. 020051.'],
  motor_1_2_05_020051_2: ['Motor fastening pin', '2 mm diameter, 4 mm long; CAD ref. 020051-2.'],
  motor_1_2_16_001425: ['Motor internal plate', 'Shaped internal component; CAD ref. 001425.'],
  revolve1_1: ['Pivot bearing outer race', '26 mm outer diameter, 5 mm wide.'],
  revolve1_2: ['Pivot bearing inner race', 'Inner ring of the leg-pivot bearing.'],
  revolve3_1: ['Pivot bearing shield', 'Cover on one side of the bearing.'],
  revolve3_2: ['Pivot bearing opposite shield', 'Cover on the opposite side of the bearing.'],
  cirpattern2: ['Bearing shield retaining ring', 'Retains the bearing shield.'],
  mirror1: ['Opposite bearing retaining ring', 'Retains the shield on the opposite side.'],
  revolve2: ['Bearing ball 1', '3.15 mm rolling element inside the pivot bearing.'],
  ...Object.fromEntries(Array.from({ length: 12 }, (_, i) => [`cirpattern1_${i + 1}`, [`Bearing ball ${i + 2}`, '3.15 mm rolling element inside the pivot bearing.']])),
  revolve1: ['Locknut insert', 'Locking insert inside the linkage nut.'],
  cut_extrude2: ['M5 linkage locknut', 'Hexagonal nut securing the linkage pivot.'],
  m3_countersunk_hex_drive_screw__8mm_l__alloy_steel: ['M3 × 8 mm countersunk screw', 'Hex drive, alloy steel.'],
  hex_socket_head_countersunk_screw_grade_c_m3x0_5_x_10: ['M3 × 10 mm countersunk screw', '0.5 mm thread pitch, hex drive.'],
  m4_countersunk_hex_drive_screw__12mm_l__alloy_steel: ['M4 × 12 mm countersunk screw', 'Hex drive, alloy steel.'],
  m3_low_profile_socket_head_screw__5mm_l__hs_steel: ['M3 × 5 mm low-profile screw', 'Socket head, high-strength steel.'],
  m3_low_profile_socket_head_screw__6mm_l__18_8_ss: ['M3 × 6 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m3_low_profile_socket_head_screw__8mm_l__18_8_ss: ['M3 × 8 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m3_low_profile_socket_head_screw__12mm_l__18_8_ss: ['M3 × 12 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m3_ultra_low_profile_socket_head_screw__12mm_l__hs_steel: ['M3 × 12 mm ultra-low-profile screw', 'Socket head, high-strength steel.'],
  m3_low_profile__socket_head_shoulder_screw__45mm_shoulder_l__4mm_l__18_8_ss: ['M3 shoulder screw', '45 mm shoulder and 4 mm threaded length, 18-8 stainless steel.'],
  m4_low_profile_socket_head_screw__4mm_l__18_8_ss: ['M4 × 4 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m4_low_profile_socket_head_screw__8mm_l__18_8_ss: ['M4 × 8 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m5_low_profile_socket_screw__10mm_l__18_8_stainless_steel: ['M5 × 10 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m5_low_profile_socket_screw__14mm_l__18_8: ['M5 × 14 mm low-profile screw', 'Socket head, 18-8 stainless steel.'],
  m5_nylon_lubricant_filled_nylon_washer__5_5mm_id__10mm_od__1mm_t: ['M5 nylon washer', '5.5 mm bore, 10 mm outer diameter, nominally 1 mm thick.'],
  m4_through_hole_standoff__8mm_l__hardened_steel: ['M4 × 8 mm through-hole standoff', 'Hardened steel spacer.'],
  pem_bsos_m3_6: ['M3 × 6 mm clinching standoff', 'PEM BSOS-M3-6 spacer.'],
  pem_m4_self_clinching_nut__300_ss: ['M4 self-clinching nut', 'PEM nut, 300-series stainless steel.'],
};

export function describePart(file) {
  const key = file.replace(/\.stl$/i, '');
  const [name, detail] = PARTS[key] || ['CAD component', `Source part: ${key}`];
  return { name, detail, motor: key.startsWith('motor_') };
}
